export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const SET_SUBMITTED = 'SET_SUBMITTED';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_TAB = 'SET_TAB';

export const SET_SUCCESS_MODAL_SHOW = 'SET_SUCCESS_MODAL_SHOW';
export const SET_SUCCESS_MODAL_MESSAGE = 'SET_SUCCESS_MODAL_MESSAGE';

export const SET_CONFIRM_MODAL_SHOW = 'SET_CONFIRM_MODAL_SHOW';
export const SET_CONFIRM_MODAL_MESSAGE = 'SET_CONFIRM_MODAL_MESSAGE';
export const SET_CONFIRM_MODAL_DECISION = 'SET_CONFIRM_MODAL_DECISION';